CREATE ROLE foo LOGIN PASSWORD 'foo';
CREATE ROLE bar LOGIN PASSWORD 'bar';
CREATE ROLE baz LOGIN PASSWORD 'baz';
CREATE ROLE zaz LOGIN PASSWORD 'zaz';

CREATE DATABASE foo OWNER foo;
CREATE DATABASE bar OWNER bar;
CREATE DATABASE baz OWNER baz;
CREATE DATABASE zaz OWNER zaz;

REVOKE CONNECT ON DATABASE australttdev FROM PUBLIC;
REVOKE CONNECT ON DATABASE australttprd FROM PUBLIC;
REVOKE CONNECT ON DATABASE australttqa FROM PUBLIC;
REVOKE CONNECT ON DATABASE invidious FROM PUBLIC;
REVOKE CONNECT ON DATABASE synapse FROM PUBLIC;
